blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("addresses/", views.addresses, name="addresses"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_address/<id>/", views.delete_address, name="delete_address"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),


    path("ckeditor5/", include('django_ckeditor_5.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.shop, name="shop"),
    path("category/<id>/", views.category, name="category"),
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("cart/", views.cart, name="cart"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),

    path("filter_products/", views.filter_products, name="filter_products"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),

    path('stripe_payment/<order_id>/', views.stripe_payment, name='stripe_payment'),
    path('stripe_payment_verify/<order_id>/', views.stripe_payment_verify, name='stripe_payment_verify'),
    path('paypal_payment_verify/<order_id>/', views.paypal_payment_verify, name='paypal_payment_verify'),
    path('razorpay_payment_verify/<order_id>/', views.razorpay_payment_verify, name='razorpay_payment_verify'),
    path('paystack_payment_verify/<order_id>/', views.paystack_payment_verify, name='paystack_payment_verify'),
    path('flutterwave_payment_callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave_payment_callback'),

    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<item_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"),

]

userauths/urls.py
from django.urls import path

from userauths import views
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

store/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives, send_mail

from decimal import Decimal
import requests
import stripe
from plugin.service_fee import calculate_service_fee
import razorpay

from plugin.paginate_queryset import paginate_queryset
from store import models as store_models
from customer import models as customer_models
from vendor import models as vendor_models
from userauths import models as userauths_models
from plugin.tax_calculation import tax_calculation
from plugin.exchange_rate import convert_usd_to_inr, convert_usd_to_kobo, convert_usd_to_ngn, get_usd_to_ngn_rate


stripe.api_key = settings.STRIPE_SECRET_KEY
razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

def clear_cart_items(request):
    try:
        cart_id = request.session['cart_id']
        store_models.Cart.objects.filter(cart_id=cart_id).delete()
    except:
        pass
    return

def index(request):
    products = store_models.Product.objects.filter(status="Published")
    categories = store_models.Category.objects.all()
    
    context = {
        "products": products,
        "categories": categories,
    }
    return render(request, "store/index.html", context)

def shop(request):
    products_list = store_models.Product.objects.filter(status="Published")
    categories = store_models.Category.objects.all()
    colors = store_models.VariantItem.objects.filter(variant__name='Color').values('title', 'content').distinct()
    sizes = store_models.VariantItem.objects.filter(variant__name='Size').values('title', 'content').distinct()
    item_display = [
        {"id": "1", "value": 1},
        {"id": "2", "value": 2},
        {"id": "3", "value": 3},
        {"id": "40", "value": 40},
        {"id": "50", "value": 50},
        {"id": "100", "value": 100},
    ]

    ratings = [
        {"id": "1", "value": "★☆☆☆☆"},
        {"id": "2", "value": "★★☆☆☆"},
        {"id": "3", "value": "★★★☆☆"},
        {"id": "4", "value": "★★★★☆"},
        {"id": "5", "value": "★★★★★"},
    ]

    prices = [
        {"id": "lowest", "value": "От высокой цены к низкой"},
        {"id": "highest", "value": "От низкой цены к высокой"},
    ]


    print(sizes)

    products = paginate_queryset(request, products_list, 10)

    context = {
        "products": products,
        "products_list": products_list,
        "categories": categories,
         'colors': colors,
        'sizes': sizes,
        'item_display': item_display,
        'ratings': ratings,
        'prices': prices,
    }
    return render(request, "store/shop.html", context)

def category(request, id):
    category = store_models.Category.objects.get(id=id)
    products_list = store_models.Product.objects.filter(status="Published", category=category)

    query = request.GET.get("q")
    if query:
        products_list = products_list.filter(name__icontains=query)

    products = paginate_queryset(request, products_list, 10)

    context = {
        "products": products,
        "products_list": products_list,
        "category": category,
    }
    return render(request, "store/category.html", context)

def vendors(request):
    vendors = userauths_models.Profile.objects.filter(user_type="Vendor")
    
    context = {
        "vendors": vendors
    }
    return render(request, "store/vendors.html", context)

def product_detail(request, slug):
    product = store_models.Product.objects.get(status="Published", slug=slug)
    product_stock_range = range(1, product.stock + 1)

    related_products = store_models.Product.objects.filter(category=product.category).exclude(id=product.id)

    context = {
        "product": product,
        "product_stock_range": product_stock_range,
        "related_products": related_products,
    }
    return render(request, "store/product_detail.html", context)

def add_to_cart(request):
    # Get parameters from the request (ID, color, size, quantity, cart_id)
    id = request.GET.get("id")
    qty = request.GET.get("qty")
    color = request.GET.get("color")
    size = request.GET.get("size")
    cart_id = request.GET.get("cart_id")
    
    request.session['cart_id'] = cart_id

    # Validate required fields
    if not id or not qty or not cart_id:
        return JsonResponse({"error": "Выберите цвет и размер"}, status=400)

    # Try to fetch the product, return an error if it doesn't exist
    try:
        product = store_models.Product.objects.get(status="Published", id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({"error": "Product not found"}, status=404)

    # Check if the item is already in the cart
    existing_cart_item = store_models.Cart.objects.filter(cart_id=cart_id, product=product).first()

    # Check if quantity that user is adding exceed item stock qty
    if int(qty) > product.stock:
        return JsonResponse({"error": "Запрашиваемое количество отсутствует"}, status=404)

    # If the item is not in the cart, create a new cart entry
    if not existing_cart_item:
        cart = store_models.Cart()
        cart.product = product
        cart.qty = qty
        cart.price = product.price
        cart.color = color
        cart.size = size
        cart.sub_total = Decimal(product.price) * Decimal(qty)
        cart.shipping = Decimal(product.shipping) * Decimal(qty)
        cart.total = cart.sub_total + cart.shipping
        cart.user = request.user if request.user.is_authenticated else None
        cart.cart_id = cart_id
        cart.save()

        message = "Товар добавлен в корзину"
    else:
        # If the item exists in the cart, update the existing entry
        existing_cart_item.color = color
        existing_cart_item.size = size
        existing_cart_item.qty = qty
        existing_cart_item.price = product.price
        existing_cart_item.sub_total = Decimal(product.price) * Decimal(qty)
        existing_cart_item.shipping = Decimal(product.shipping) * Decimal(qty)
        existing_cart_item.total = existing_cart_item.sub_total +  existing_cart_item.shipping
        existing_cart_item.user = request.user if request.user.is_authenticated else None
        existing_cart_item.cart_id = cart_id
        existing_cart_item.save()

        message = "Корзина обновлена"

    # Count the total number of items in the cart
    total_cart_items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']

    # Return the response with the cart update message and total cart items
    return JsonResponse({
        "message": message ,
        "total_cart_items": total_cart_items.count(),
        "cart_sub_total": "{:,.2f}".format(cart_sub_total),
        "item_sub_total": "{:,.2f}".format(existing_cart_item.sub_total) if existing_cart_item else "{:,.2f}".format(cart.sub_total) 
    })

def cart(request):
    if "cart_id" in request.session:
        cart_id = request.session['cart_id']
    else:
        cart_id = None

    items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']
    
    try:
        addresses = customer_models.Address.objects.filter(user=request.user)
    except:
        addresses = None

    if not items:
        messages.warning(request, "В корзине нет товаров")
        return redirect("store:index")

    context = {
        "items": items,
        "cart_sub_total": cart_sub_total,
        "addresses": addresses,
    }
    return render(request, "store/cart.html", context)

def delete_cart_item(request):
    id = request.GET.get("id")
    item_id = request.GET.get("item_id")
    cart_id = request.GET.get("cart_id")
    
    # Validate required fields
    if not id and not item_id and not cart_id:
        return JsonResponse({"error": "Item or Product id not found"}, status=400)

    try:
        product = store_models.Product.objects.get(status="Published", id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({"error": "Product not found"}, status=404)

    # Check if the item is already in the cart
    item = store_models.Cart.objects.get(product=product, id=item_id)
    item.delete()

    # Count the total number of items in the cart
    total_cart_items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']

    return JsonResponse({
        "message": "Товар убран из корзины",
        "total_cart_items": total_cart_items.count(),
        "cart_sub_total": "{:,.2f}".format(cart_sub_total) if cart_sub_total else 0.00
    })

def create_order(request):
    if request.method == "POST":
        address_id = request.POST.get("address")
        if not address_id:
            messages.warning(request, "Выберите адрес, чтобы продолжить")
            return redirect("store:cart")
        
        address = customer_models.Address.objects.filter(user=request.user, id=address_id).first()

        if "cart_id" in request.session:
            cart_id = request.session['cart_id']
        else:
            cart_id = None

        items = store_models.Cart.objects.filter(cart_id=cart_id)
        cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']
        cart_shipping_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(shipping = models.Sum("shipping"))['shipping']
        
        order = store_models.Order()

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
    <head>
        <meta charset="utf-8" />
        <meta name="author" content="Ecommerce" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>E-commerce</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    </head>

    <body>
        <div id="main-wrapper">
            <div class="header header-dark dark-text">
                <div class="container">
                    <nav id="navigation" class="navigation navigation-landscape">
                        <div class="nav-header">
                            <a class="nav-brand" href="{% url 'store:index' %}">
                                <img style="width: 340px; object-fit: contain;" src="{% static 'C:\Users\777\Desktop\FastCart-Ecommerce-Django--master\static\assets\logo.jpg' %}" class="logo" alt="" />
                            </a>
                            <div class="nav-toggle"></div>
                            <div class="mobile_nav">
                                <ul>
                                    <li>
                                        <a href="#"><i class="fas fa-search-alt"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fas fa-user"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"> <i class="fas fa-heart text-white"></i><span class="dn-counter">2</span> </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'store:cart' %}"> <i class="fas fa-shopping-basket"></i><span class="dn-counter total_cart_items">{{total_cart_items}}</span> </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="nav-menus-wrapper" style="transition-property: none">
                            <ul class="nav-menu">
                                <li><a href="/">Главная</a></li>
                                <li>
                                    <a href="{% url 'store:shop' %}">Лавка</a>
                                </li>
                                 <li>
                                    <a href="javascript:void(0);">Категория</a>
                                    <ul class="nav-dropdown nav-submenu">
                                        
                                        {% for c in category_ %}
                                            <li><a href="{% url 'store:category' c.id %}">{{c.title}}</a></li>
                                        {% endfor %}
                                            
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">Продавец</a>
                                    <ul class="nav-dropdown nav-submenu">
                                        <li><a href="{% url 'vendor:dashboard' %}">Управление</a></li>
                                        <li><a href="{% url 'vendor:products' %}">Товары</a></li>
                                        <li><a href="{% url 'vendor:create_product' %}">Добавить товар</a></li>
                                        <li><a href="{% url 'vendor:orders' %}">Заказы</a></li>
                                        <li><a href="{% url 'vendor:coupons' %}">Купоны</a></li>
                                        <li><a href="{% url 'vendor:notis' %}">Уведомления</a></li>
                                        <li><a href="{% url 'vendor:reviews' %}">Отзывы</a></li>

                                        <li><a href="{% url 'vendor:profile' %}">Профиль</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">Клиент</a>
                                    <ul class="nav-dropdown nav-submenu">
                                        <li><a href="{% url 'customer:dashboard' %}">Личный Кабинет</a></li>
                                        <li><a href="{% url 'customer:orders' %}">Мои заказы</a></li>
                                        <li><a href="{% url 'customer:wishlist' %}">Мой Вишлист</a></li>
                                        <li><a href="{% url 'customer:addresses' %}">Адрес</a></li>
                                        <li><a href="{% url 'customer:notis' %}">Уведомления</a></li>
                                        <li><a href="{% url 'customer:profile' %}">Профиль</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">Информация</a>
                                    <ul class="nav-dropdown nav-submenu">
                                        <li><a href="{% url 'blog:blog_list' %}">Блог</a></li>
                                        <li><a href="{% url 'store:about' %}">О нас</a></li>
                                        <li><a href="{% url 'store:contact' %}">Контакты</a></li>
                                        <li><a href="{% url 'store:faqs' %}">Частые вопросы</a></li>
                                        <li><a href="{% url 'store:privacy_policy' %}">Конфиденциальность</a></li>
                                        <li><a href="{% url 'store:terms_conditions' %}">Условия использования</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="{% url 'store:order_tracker_page' %}">Отследить<i class="fas fa-truck ms-1"></i></a>
                                </li>
                            </ul>

                            <ul class="nav-menu nav-menu-social align-to-right">
                                <li>
                                    <a href="{% url 'store:shop' %}"><i class="fas fa-search text-white"></i></a>
                                </li>
                               
                               {% if request.user.is_authenticated %}
                                     <li>
                                        <a href="{% url 'customer:dashboard' %}"><i class="fas fa-user text-white"></i></a>
                                    </li>
                                    <li>
                                        <a href="{% url 'customer:wishlist' %}"><i class="fas fa-heart text-white"></i><span class="dn-counter">{{ wishlist_count.count }}</span> </a>
                                    </li>
                               {% endif %}
                                
                                <li>
                                    <a href="{% url 'store:cart' %}"><i class="fas fa-shopping-basket text-white"></i><span class="dn-counter total_cart_items">{{total_cart_items}}</span> </a>
                                </li>
                                
                                {% if request.user.is_authenticated %}
                                    
                                    <li>
                                        <a href="{% url 'userauths:sign-out' %}" class="btn bg-primary py-2 px-4 rounded text-white"><i class="fas fa-sign-out-alt me-1"></i>Выход</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{% url 'userauths:sign-in' %}" class="btn bg-primary py-2 px-4 rounded text-white">Войти<i class="fas fa-sign-in-alt ms-1"></i></a>
                                    </li>
                                    <li>
                                        <a href="{% url 'userauths:sign-up' %}" class="btn bg-primary py-2 px-4 rounded text-white">Регистрация <i class="fas fa-user-plus ms-1"></i></a>
                                    </li>
                                {% endif %}
                                    
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

           
           {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show text-center" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
           {% endfor %}
            

            {% block content %} {% endblock content %}

            <footer class="dark-footer skin-dark-footer" style="margin-top: 500px">
                <div class="footer-middle">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-4 col-lg-4 col-md-3 col-sm-12">
                                <div class="footer_widget">
                                    <img src="{% static '' %}" class="img-footer small mb-2" alt="" />

                                    <div class="address mt-3">Казахстан <br />Алматы</div>
                                    <div class="address mt-3">+7 747 638 56 74<br />aymen.zhanabayeva@mail.ru</div>
                                    <div class="address mt-3">
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <a href="#"><i class="fab fa-facebook"></i></a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a href="#"><i class="fab fa-twitter"></i></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xl-4 col-lg-4 col-md-2 col-sm-12">
                                <div class="footer_widget">
                                    <h4 class="widget_title">Поддержка</h4>
                                    <ul class="footer-menu">
                                        <li><a href="#">Связаться с нами</a></li>
                                        <li><a href="#">О нас</a></li>
                                        <li><a href="#">Часто задаваемые вопросы</a></li>
                                        <li><a href="#">Безопасность данных</a></li>
                                        <li><a href="#">Условия использования</a></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="col-xl-4 col-lg-4 col-md-3 col-sm-12">
                                <div class="footer_widget">
                                    <h4 class="widget_title">Подпишитесь на волшебство! 💌</h4>
                                    <p>Персональные скидки и вдохновение в каждом письме.</p>
                                    <div class="foot-news-last">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Email Address" />
                                            <div class="input-group-append">
                                                <button type="button" class="input-group-text b-0 text-light"><i class="fas fa-arrow-right"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/ion.rangeSlider.min.js' %}"></script>
        <script src="{% static 'assets/js/slick.js' %}"></script>
        <script src="{% static 'assets/js/slider-bg.js' %}"></script>
        <script src="{% static 'assets/js/lightbox.js' %}"></script>
        <script src="{% static 'assets/js/smoothproducts.js' %}"></script>
        <script src="{% static 'assets/js/snackbar.min.js' %}"></script>
        <script src="{% static 'assets/js/jQuery.style.switcher.js' %}"></script>
        <script src="{% static 'assets/js/custom.js' %}"></script>
        <script src="{% static 'assets/js/function.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    </body>
</html>