blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("addresses/", views.addresses, name="addresses"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_address/<id>/", views.delete_address, name="delete_address"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),


    path("ckeditor5/", include('django_ckeditor_5.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.shop, name="shop"),
    path("category/<id>/", views.category, name="category"),
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("cart/", views.cart, name="cart"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),

    path("filter_products/", views.filter_products, name="filter_products"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),

    path('stripe_payment/<order_id>/', views.stripe_payment, name='stripe_payment'),
    path('stripe_payment_verify/<order_id>/', views.stripe_payment_verify, name='stripe_payment_verify'),
    path('paypal_payment_verify/<order_id>/', views.paypal_payment_verify, name='paypal_payment_verify'),
    path('razorpay_payment_verify/<order_id>/', views.razorpay_payment_verify, name='razorpay_payment_verify'),
    path('paystack_payment_verify/<order_id>/', views.paystack_payment_verify, name='paystack_payment_verify'),
    path('flutterwave_payment_callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave_payment_callback'),

    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<item_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"),

]

userauths/urls.py
from django.urls import path

from userauths import views
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

customer/models.py
from django.db import models

from store.models import Product
from userauths.models import User


TYPE = (
    ("New Order", "New Order"),
    ("Item Shipped", "Item Shipped"),
    ("Item Delivered", "Item Delivered"),
)

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="wishlist")
    
    class Meta:
        verbose_name_plural = "Wishlist"
    
    def __str__(self):
        if self.product.name:
            return self.product.name
        else:
            return "Wishlist"
        
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=200, null=True, blank=True, default=None)
    mobile = models.CharField(max_length=50, null=True, blank=True, default=None)
    email = models.CharField(max_length=100, null=True, blank=True, default=None)
    country = models.CharField(max_length=100, null=True, blank=True, default=None)
    state = models.CharField(max_length=100, null=True, blank=True, default=None)
    city = models.CharField(max_length=100, null=True, blank=True, default=None)
    address = models.CharField(max_length=100, null=True, blank=True, default=None)
    zip_code = models.CharField(max_length=100, null=True, blank=True, default=None)
    
    class Meta:
        verbose_name_plural = "Customer Address"
    
    def __str__(self):
        return self.full_name



class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    type = models.CharField(max_length=100, choices=TYPE, default=None)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Notification"
    
    def __str__(self):
        return self.type

store/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils import timezone
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

from userauths import models as user_models
from vendor import models as vendor_models

import shortuuid

STATUS = (
    ("Published", "Published"),
    ("Draft", "Draft"),
    ("Disabled", "Disabled"),
)

PAYMENT_STATUS = (
    ("Paid", "Оплачен"),
    ("Processing", "Обработка"),
    ("Failed", "Не удалось"),
)


PAYMENT_METHOD = (
    ("PayPal", "PayPal"),
    ("Stripe", "Stripe"),
    ("Flutterwave", "Flutterwave"),
    ("Paystack", "Paystack"),
    ("RazorPay", "RazorPay"),
)

ORDER_STATUS = (
    ("Pending", "В ожидании"),
    ("Processing", "В обработке"),
    ("Shipped", "Отправлен"),
    ("Fulfilled", "Выполнен"),
    ("Cancelled", "Отменён"),
)


SHIPPING_SERVICE = (
    ("DHL", "DHL"),
    ("FedX", "FedX"),
    ("UPS", "UPS"),
    ("GIG Logistics", "GIG Logistics")
)


RATING = (
    ( 1,  "★☆☆☆☆"),
    ( 2,  "★★☆☆☆"),
    ( 3,  "★★★☆☆"),
    ( 4,  "★★★★☆"),
    ( 5,  "★★★★★"),
)

class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images", default="category.jpg", null=True, blank=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title
    
    def products(self):
        return Product.objects.filter(category=self)
    
class Product(models.Model):
    name = models.CharField(max_length=100)
    image = models.FileField(upload_to="images", blank=True, null=True, default="product.jpg")
    description = CKEditor5Field('Text', config_name='extends')
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)

    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Sale Price")
    regular_price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Regular Price")

    stock = models.PositiveIntegerField(default=0, null=True, blank=True)
    shipping = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Shipping Amount")
    
    status = models.CharField(choices=STATUS, max_length=50, default="Published")
    featured = models.BooleanField(default=False, verbose_name="Marketplace Featured")
    
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, blank=True)
    
    sku = ShortUUIDField(unique=True, length=5, max_length=50, prefix="SKU", alphabet="1234567890")
    slug = models.SlugField(null=True, blank=True)
    
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name
    
    def average_rating(self):
        return Review.objects.filter(product=self).aggregate(avg_rating=models.Avg('rating'))['avg_rating']
    
    def reviews(self):
        return Review.objects.filter(product=self)

    def gallery(self):
        return Gallery.objects.filter(product=self)
  
    def variants(self):
        return Variant.objects.filter(product=self)

    def vendor_orders(self):
        return OrderItem.objects.filter(product=self, vendor=self.vendor)

    def save(self, *args, **kwargs):
        if not self.slug :
            self.slug = slugify(self.name) + "-" + str(shortuuid.uuid().lower()[:2])
            
        super(Product, self).save(*args, **kwargs) 

class Variant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=1000, verbose_name="Variant Name", null=True, blank=True)

    def items(self):
        return VariantItem.objects.filter(variant=self)
    
    def __str__(self):
        return self.name

class VariantItem(models.Model):
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name='variant_items')
    title = models.CharField(max_length=1000, verbose_name="Item Title", null=True, blank=True)
    content = models.CharField(max_length=1000, verbose_name="Item Content", null=True, blank=True)

    def __str__(self):
        return self.variant.name
    
class Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    image = models.FileField(upload_to="images", default="gallery.jpg")
    gallery_id = ShortUUIDField(length=6, max_length=10, alphabet="1234567890")

    def __str__(self):
        return f"{self.product.name} - image"

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, blank=True)
    qty = models.PositiveIntegerField(default=0, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    sub_total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    shipping = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    tax = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    size = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)
    cart_id = models.CharField(max_length=1000, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.cart_id} - {self.product.name}'

class Coupon(models.Model):
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=100)
    discount = models.IntegerField(default=1)
    
    def __str__(self):
        return self.code

class Order(models.Model):
    vendors = models.ManyToManyField(user_models.User, blank=True)
    customer = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, related_name="customer", blank=True)
    sub_total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    shipping = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    tax = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    service_fee = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    payment_status = models.CharField(max_length=100, choices=PAYMENT_STATUS, default="Processing")
    payment_method = models.CharField(max_length=100, choices=PAYMENT_METHOD, default=None, null=True, blank=True)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS, default="Pending")
    initial_total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, help_text="The original total before discounts")
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, help_text="Amount saved by customer")
    address = models.ForeignKey("customer.Address", on_delete=models.SET_NULL, null=True)
    coupons = models.ManyToManyField(Coupon, blank=True)
    order_id = ShortUUIDField(length=6, max_length=25, alphabet="1234567890")
    payment_id = models.CharField(null=True, blank=True, max_length=1000)
    date = models.DateTimeField(default=timezone.now)
    
    class Meta:
        verbose_name_plural = "Order"
        ordering = ['-date']

    def __str__(self):
        return self.order_id

    def order_items(self):
        return OrderItem.objects.filter(order=self)
    
    
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS, default="Pending")
    shipping_service = models.CharField(max_length=100, choices=SHIPPING_SERVICE, default=None, null=True, blank=True)
    tracking_id = models.CharField(max_length=100, default=None, null=True, blank=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)
    color = models.CharField(max_length=100, null=True, blank=True)
    size = models.CharField(max_length=100, null=True, blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    sub_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    shipping = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    tax = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    initial_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, help_text="Grand Total of all amount listed above before discount")
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, help_text="Amount saved by customer")
    coupon = models.ManyToManyField(Coupon, blank=True)
    applied_coupon = models.BooleanField(default=False)
    item_id = ShortUUIDField(length=6, max_length=25, alphabet="1234567890")
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, related_name="vendor_order_items")
    date = models.DateTimeField(default=timezone.now)

    def order_id(self):
        return f"{self.order.order_id}"
  
    def __str__(self):
        return self.item_id
    
    class Meta:
        ordering = ['-date']

class Review(models.Model):
    user = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True, related_name="reviews")

templates/customer/dashboard.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}
<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'customer:dashboard' %}">Клиент</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Управление</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row align-items-start justify-content-between">
             {% include 'customer/sidebar.html' %}

            <div class="col-12 col-md-12 col-lg-8 col-xl-8">
                <div class="row mb-4">
                    <h4 class="mb-0 mb-4 fw-bold">Управление </h4>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-shopping-cart text-danger"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">{{orders.count}}</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Заказы</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-wallet text-warning"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">{{total_spent|floatformat:2|intcomma|default:"0.00"}} ₸</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Общие расходы</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                        <div class="d-flex justify-content-center align-items-center p-4 shadow-sm rounded">
                            <span class="display-6 text-danger">
                                <i class="fas fa-bell text-primary"></i>
                            </span>
                            <div class="ms-4">
                                <div class="d-flex">
                                    <h5 class="mb-0 fw-bold">{{notis.count}}</h5>
                                </div>
                                <p class="mb-0 h6 fw-semibold">Уведомления</p>
                            </div>
                        </div>
                    </div>
                </div>

                
                {% for order in orders %}
                    <div class="ord_list_wrap border mb-4 mfliud">
                        <div class="ord_list_head bg-light bg-opacity-10 d-flex align-items-center justify-content-between px-3 py-3">
                            <div class="olh_flex">
                                <p class="m-0 p-0"><span class="text-muted">Номер заказа</span></p>
                                <h6 class="mb-0 ft-medium">#{{order.order_id}}</h6>
                            </div>
                            <div class="olh_flex">
                                <a href="{% url 'customer:order_detail' order.order_id %}" class="btn btn-sm bg-primary rounded text-white"> Просмотр заказа <i class="fas fa-arrow-right ms-2"></i></a>
                                
                                {% if order.payment_status == "Failed" %}
                                    <a href="{% url 'store:checkout' order.order_id %}" class="btn btn-sm bg-danger rounded text-white">Повторить оплату <i class="fas fa-rotate ms-2"></i></a>
                                {% endif %}
                                    
                            </div>
                        </div>
                        <div class="ord_list_body text-left">
                            <!-- Single Item -->
                            
                            {% for item in order.order_items.all %}
                                <div class="row align-items-center justify-content-center m-0 py-4 br-bottom">
                                    <div class="col-xl-6 col-lg-5 col-md-5 col-12">
                                        <div class="cart_single d-flex align-items-start mfliud-bot gap-3">
                                            <div class="cart_selected_single_thumb">
                                                <a href="{% url 'store:product_detail' item.product.slug %}"><img src="{{item.product.image.url}}" width="75" class="img-fluid rounded" alt="" /></a>
                                            </div>
                                            <div class="cart_single_caption pl-3">
                                                <h4 class="product_title fs-sm ft-medium mb-1 lh-1"> <a href="{% url 'store:product_detail' item.product.slug %}">{{item.product.name}}</a></h4>
                                                <p class="mb-2">
                                                    <span class="text-dark medium">Продавец: {{item.product.vendor.profile.full_name}}</span> <br />
                                                    
                                                    {% if item.color %}
                                                        <span class="text-dark medium">Цвет: {{item.color}}</span>
                                                    {% endif %}

                                                    {% if item.size %}
                                                        <span class="text-dark medium">Размер: {{item.size}}</span>
                                                    {% endif %}
                                                        
                                                </p>
                                                <h4 class="fs-sm ft-bold mb-0 lh-1">{{item.price}} ₸</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-2 col-lg-3 col-md-3 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Статус</span></p>
                                        <div class="delv_status"><span class="ft-medium small text-warning bg-light-warning rounded px-3 py-1">{{ item.get_order_status_display }}</span></div>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Статус Оплаты</span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{ order.get_payment_status_display }}</h6>
                                    </div>
                                    <div class="col-xl-2 col-lg-4 col-md-4 col-6">
                                        <p class="mb-1 p-0"><span class="text-muted">Дата/время заказа </span></p>
                                        <h6 class="mb-0 ft-medium fs-sm">{{order.date}}</h6>
                                    </div>
                                </div>
                            {% endfor %}
                                
                        </div>
                        <div class="ord_list_footer d-flex align-items-center justify-content-between br-top px-3">
                            <div class="col-xl-12 pr-0 py-2 olf_flex d-flex align-items-center justify-content-between">
                                <div class="olf_flex_inner hide_mob">
                                    <p class="m-0 p-0"><span class="text-muted medium">Оплата: {{order.payment_method}}</span></p>
                                </div>
                                <div class="float-end"><h5 class="mb-0 fs-sm ft-bold">К оплате: {{order.total|floatformat:2|intcomma}} ₸</h5></div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                <p>No orders yet</p>
                {% endfor %}
                    
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/customer/sidebar.html
<div class="col-12 col-md-12 col-lg-4 col-xl-4 miliods">
    <div class="d-block border p-2 rounded">
        <div class="dashboard_author px-2 py-5">
            <div class="dash_auth_thumb circle p-1 border d-inline-flex mx-auto mb-2">
                <img src="{{request.user.profile.image.url}}" class="img-fluid circle" style="width: 100px; height: 100px; object-fit: cover;" alt="" />
            </div>
            <div class="dash_caption">
                <h4 class="fs-md ft-medium mb-0 lh-1">{{request.user.profile.full_name}}</h4>
                <span class="text-muted smalls">Клиент ID: #{{request.user.id}}</span>
            </div>
        </div>

        <div class="dashboard_author">
            <h4 class="px-3 py-2 mb-0 lh-2 gray fs-sm ft-medium text-muted text-uppercase text-left">Панель навигации </h4>
            <ul class="dahs_navbar">
                <li>
                    <a href="{% url 'customer:dashboard' %}" class="{% if '/customer/dashboard/' in request.path %} active{% endif %}"><i class="bi bi-grid-fill me-2"></i>Управление</a>
                </li>
                <li>
                    <a href="{% url 'customer:orders' %}" class="{% if '/customer/orders/' in request.path or '/customer/order_detail/' in request.path %} active{% endif %}"><i class="fas fa-shopping-basket me-2"></i>Заказы</a>
                </li>
                <li>
                    <a href="{% url 'customer:wishlist' %}" class="{% if '/customer/wishlist/' in request.path %} active{% endif %}"><i class="fas fa-heart me-2"></i>Мой вишлист </a>
                </li>
                <li>
                    <a href="{% url 'customer:addresses' %}" class="{% if '/customer/addresses/' in request.path or '/customer/address_detail/' in request.path or '/customer/address_create/' in request.path %} active {% endif %}"><i class="fas fa-map-marker me-2"></i>Адрес</a>
                </li>

                <li>
                    <a href="{% url 'customer:profile' %}" class="{% if '/customer/profile/' in request.path %} active{% endif %}"><i class="fas fa-user me-2"></i>Профиль</a>
                </li>
                <li>
                    <a href="{% url 'userauths:sign-out' %}"><i class="fas fa-power-off me-2"></i>Выйти</a>
                </li>
            </ul>
        </div>
    </div>
</div>