blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("addresses/", views.addresses, name="addresses"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_address/<id>/", views.delete_address, name="delete_address"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),


    path("ckeditor5/", include('django_ckeditor_5.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.shop, name="shop"),
    path("category/<id>/", views.category, name="category"),
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("cart/", views.cart, name="cart"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),

    path("filter_products/", views.filter_products, name="filter_products"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),

    path('stripe_payment/<order_id>/', views.stripe_payment, name='stripe_payment'),
    path('stripe_payment_verify/<order_id>/', views.stripe_payment_verify, name='stripe_payment_verify'),
    path('paypal_payment_verify/<order_id>/', views.paypal_payment_verify, name='paypal_payment_verify'),
    path('razorpay_payment_verify/<order_id>/', views.razorpay_payment_verify, name='razorpay_payment_verify'),
    path('paystack_payment_verify/<order_id>/', views.paystack_payment_verify, name='paystack_payment_verify'),
    path('flutterwave_payment_callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave_payment_callback'),

    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<item_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"),

]

userauths/urls.py
from django.urls import path

from userauths import views
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

store/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils import timezone
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

from userauths import models as user_models
from vendor import models as vendor_models

import shortuuid

STATUS = (
    ("Published", "Published"),
    ("Draft", "Draft"),
    ("Disabled", "Disabled"),
)

PAYMENT_STATUS = (
    ("Paid", "Оплачен"),
    ("Processing", "Обработка"),
    ("Failed", "Не удалось"),
)


PAYMENT_METHOD = (
    ("PayPal", "PayPal"),
    ("Stripe", "Stripe"),
    ("Flutterwave", "Flutterwave"),
    ("Paystack", "Paystack"),
    ("RazorPay", "RazorPay"),
)

ORDER_STATUS = (
    ("Pending", "В ожидании"),
    ("Processing", "В обработке"),
    ("Shipped", "Отправлен"),
    ("Fulfilled", "Выполнен"),
    ("Cancelled", "Отменён"),
)


SHIPPING_SERVICE = (
    ("DHL", "DHL"),
    ("FedX", "FedX"),
    ("UPS", "UPS"),
    ("GIG Logistics", "GIG Logistics")
)


RATING = (
    ( 1,  "★☆☆☆☆"),
    ( 2,  "★★☆☆☆"),
    ( 3,  "★★★☆☆"),
    ( 4,  "★★★★☆"),
    ( 5,  "★★★★★"),
)

class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images", default="category.jpg", null=True, blank=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title
    
    def products(self):
        return Product.objects.filter(category=self)
    
class Product(models.Model):
    name = models.CharField(max_length=100)
    image = models.FileField(upload_to="images", blank=True, null=True, default="product.jpg")
    description = CKEditor5Field('Text', config_name='extends')
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)

    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Sale Price")
    regular_price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Regular Price")

    stock = models.PositiveIntegerField(default=0, null=True, blank=True)
    shipping = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, verbose_name="Shipping Amount")
    
    status = models.CharField(choices=STATUS, max_length=50, default="Published")
    featured = models.BooleanField(default=False, verbose_name="Marketplace Featured")
    
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, blank=True)
    
    sku = ShortUUIDField(unique=True, length=5, max_length=50, prefix="SKU", alphabet="1234567890")
    slug = models.SlugField(null=True, blank=True)
    
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name
    
    def average_rating(self):
        return Review.objects.filter(product=self).aggregate(avg_rating=models.Avg('rating'))['avg_rating']
    
    def reviews(self):
        return Review.objects.filter(product=self)

    def gallery(self):
        return Gallery.objects.filter(product=self)
  
    def variants(self):
        return Variant.objects.filter(product=self)

    def vendor_orders(self):
        return OrderItem.objects.filter(product=self, vendor=self.vendor)

    def save(self, *args, **kwargs):
        if not self.slug :
            self.slug = slugify(self.name) + "-" + str(shortuuid.uuid().lower()[:2])
            
        super(Product, self).save(*args, **kwargs) 

class Variant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=1000, verbose_name="Variant Name", null=True, blank=True)

    def items(self):
        return VariantItem.objects.filter(variant=self)
    
    def __str__(self):
        return self.name

class VariantItem(models.Model):
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name='variant_items')
    title = models.CharField(max_length=1000, verbose_name="Item Title", null=True, blank=True)
    content = models.CharField(max_length=1000, verbose_name="Item Content", null=True, blank=True)

    def __str__(self):
        return self.variant.name
    
class Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    image = models.FileField(upload_to="images", default="gallery.jpg")
    gallery_id = ShortUUIDField(length=6, max_length=10, alphabet="1234567890")

    def __str__(self):
        return f"{self.product.name} - image"

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, blank=True)
    qty = models.PositiveIntegerField(default=0, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    sub_total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    shipping = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    tax = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    size = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)
    cart_id = models.CharField(max_length=1000, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.cart_id} - {self.product.name}'

class Coupon(models.Model):
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=100)
    discount = models.IntegerField(default=1)
    
    def __str__(self):
        return self.code

class Order(models.Model):
    vendors = models.ManyToManyField(user_models.User, blank=True)
    customer = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, related_name="customer", blank=True)
    sub_total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    shipping = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    tax = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    service_fee = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    payment_status = models.CharField(max_length=100, choices=PAYMENT_STATUS, default="Processing")
    payment_method = models.CharField(max_length=100, choices=PAYMENT_METHOD, default=None, null=True, blank=True)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS, default="Pending")
    initial_total = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, help_text="The original total before discounts")
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, help_text="Amount saved by customer")
    address = models.ForeignKey("customer.Address", on_delete=models.SET_NULL, null=True)
    coupons = models.ManyToManyField(Coupon, blank=True)
    order_id = ShortUUIDField(length=6, max_length=25, alphabet="1234567890")
    payment_id = models.CharField(null=True, blank=True, max_length=1000)
    date = models.DateTimeField(default=timezone.now)
    
    class Meta:
        verbose_name_plural = "Order"
        ordering = ['-date']

    def __str__(self):
        return self.order_id

    def order_items(self):
        return OrderItem.objects.filter(order=self)
    
    
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS, default="Pending")
    shipping_service = models.CharField(max_length=100, choices=SHIPPING_SERVICE, default=None, null=True, blank=True)
    tracking_id = models.CharField(max_length=100, default=None, null=True, blank=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)
    color = models.CharField(max_length=100, null=True, blank=True)
    size = models.CharField(max_length=100, null=True, blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    sub_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    shipping = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    tax = models.DecimalField(default=0.00, max_digits=12, decimal_places=2)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    initial_total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, help_text="Grand Total of all amount listed above before discount")
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00, null=True, blank=True, help_text="Amount saved by customer")
    coupon = models.ManyToManyField(Coupon, blank=True)
    applied_coupon = models.BooleanField(default=False)
    item_id = ShortUUIDField(length=6, max_length=25, alphabet="1234567890")
    vendor = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True, related_name="vendor_order_items")
    date = models.DateTimeField(default=timezone.now)

    def order_id(self):
        return f"{self.order.order_id}"
  
    def __str__(self):
        return self.item_id
    
    class Meta:
        ordering = ['-date']

class Review(models.Model):
    user = models.ForeignKey(user_models.User, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True, related_name="reviews")

templates/store/cart.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Главная</a></li>
                        <li class="breadcrumb-item"><a href="/shop.html">Лавка</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Корзина</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="sec_title position-relative text-center">
                    <h3 class="ft-bold pt-3">Корзина</h3>
                </div>
            </div>
        </div>

        <form action="{% url 'store:create_order' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-9">
                    <h4 class="fw-bold p-3">Товары в корзине</h4>
                    <div style="overflow-y: scroll; max-height: 650px; overflow-x: hidden" class="p-3">
                        {% for item in items %}
                            <div class="shadow rounded mb-3 item_div_{{item.id}}">
                                <div class="row d-flex align-items-center p-3">
                                    <div class="col-lg-4 d-flex gap-3">
                                        <img src="{{item.product.image.url}}" alt="" style="width: 100px; height: 100px; object-fit: cover" />
                                        <div class="p-2">
                                            <h5>{{item.product.name}}</h5>
                                            <p class="mb-0 mt-0">Цена: {{item.price|intcomma}} ₸</p>
                                            <p class="mb-0 mt-0">Продавец: {{item.product.vendor.profile.full_name}}</p>
                                        </div>
                                    </div> 
                                    <div class="col-lg-2">
                                        <h4 class="fs-3">{{ item.price|intcomma }} ₸</h4>
                                    </div>
                                    <div class="col-lg-2 d-flex">
                                        <button type="button" class="btn bg-primary text-white btn-sm update_cart_qty" data-update_type="decrease" data-product_id="{{item.product.id}}" data-item_id="{{item.id}}">-</button>
                                        <input type="number" readonly class="form-control form-sm item-qty-{{item.id}}" value="{{item.qty}}" name="" id="" />
                                        <button type="button" class="btn bg-primary text-white btn-sm update_cart_qty" data-update_type="increase" data-product_id="{{item.product.id}}" data-item_id="{{item.id}}">+</button>
                                    </div>
                                    <div class="col-lg-2">
                                        <h4 class="fs-3 mb-0">₸ <span class="item_sub_total_{{item.id}}">{{item.sub_total|intcomma}}</span></h4>
                                    </div>
                                    <div class="col-lg-2">
                                        <button type="button" class="btn bg-danger text-white btn-sm rounded delete_cart_item" data-item_id="{{item.id}}" data-product_id="{{item.product.id}}" ><i class="fas fa-trash"></i></button>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="p-3">
                    <h4 class="fw-bold mb-3">Информация о доставке</h4>
                        {% if request.user.is_authenticated %}
                            
                            {% if addresses %}
                                <div class="row">
                                    {% for address in addresses %}
                                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                                            <div class="card-wrap border rounded mb-4">
                                                <div class="card-wrap-header px-3 py-2 br-bottom d-flex align-items-center justify-content-between">
                                                    <div class="card-heafder-flex">
                                                        <h4 class="fs-md ft-bold mb-1">Адрес Доставки <a href="{% url 'customer:address_detail' address.id %}"><i class="fas fa-edit"></i></a></h4>
                                                    </div>
                                                </div>
                                                <div class="card-wrap-body px-3 py-3">
                                                    <p class="mb-0"><span class="fw-bold">ФИО: </span>{{address.full_name}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Email: </span>{{address.email}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Телефон: </span>{{address.mobile}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Адрес:  </span>{{address.address}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Город: </span> {{address.city}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Регион: </span> {{address.state}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Страна: </span> {{address.country}}</p>
                                                    <div class="mt-3">
                                                        <input id="address{{address.id}}" value="{{address.id}}" class="radio-custom" name="address" type="radio">
                                                        <label for="address{{address.id}}" class="radio-custom-label">Выбрать Адрес</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <p>Нет сохранённых адресов, <a href="{% url 'customer:address_create' %}" class="text-primary">создать новый адрес.</a></p>
                            {% endif %}
                                
                        {% else %}
                        <p><a href="{% url 'userauths:sign-in' %}?next={{request.path}}" class="text-primary">Войдите </a> или <a class="text-primary" href="{% url 'userauths:sign-up' %}?next={{request.path}}">создайте аккаунт </a> чтобы продолжить</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="shadow rounded p-3">
                        <h4 class="fw-bold">Итоги Заказа</h4>

                        <div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Сумма заказа</p>
                                <p class="fs-6"><span class="cart_sub_total">{{cart_sub_total|intcomma}} ₸</span></p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Доставка</p>
                                <p class="fs-6">0 ₸</p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Налог</p>
                                <p class="fs-6">0 ₸</p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-3">
                                <p class="fw-bold text-dark fs-5">Итого к оплате</p>
                                <p class="fw-bold text-dark fs-5"> <span class="cart_sub_total">{{cart_sub_total|intcomma}} ₸</span></p>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-center w-100 mt-3">
                        {% if request.user.is_authenticated %}
                            <button type="submit" class="btn bg-primary rounded text-white w-100"> Оформить Заказ <i class="fas fa-arrow-right ms-1"></i></button>
                        {% else %}
                            <div>
                                <a href="{% url 'userauths:sign-in' %}?next={{request.path}}" class="btn bg-primary rounded text-white w-100 mb-3">Войти для продолжения <i class="fas fa-sign-in-alt ms-1"></i></a>
                                <a href="{% url 'userauths:sign-up' %}?next={{request.path}}" class="rounded w-100 mt-3">Создать аккаунт <i class="fas fa-user-plus ms-1"></i></a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

{% endblock content %}

templates/store/order_tracker_page.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'store:shop' %}">Лавка</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Отследить</li>
                    </ol>
            </div>
        </div>
    </div>
</div>

<section class="middle" style="margin-bottom: 600px;">
    <div class="container">
        <div class="row justify-content-center">
            <form class="col-12 col-md-10 col-lg-12 col-xl-12 text-center" method="POST">
                {% csrf_token %}
                <div class="p-4 d-inline-flex align-items-center justify-content-center circle bg-light-primary text-success mx-auto mb-4"><i class="fas fa-truck fs-1"></i></div>
                <h2 class="mb-2 ft-bold">Отслеживание заказа</h2>
                <div class="d-flex align-items-center justify-content-center">
                    <input type="text"  name="item_id" class="form-control rounded w-50" placeholder="Введите номер отслеживания, чтобы узнать, где ваш заказ" id="">
                </div>
                <button type="submit" class="btn btn-sm rounded text-white bg-primary mt-3">Узнать статус <i class="fas fa-arrow-right ms-1"></i></button>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/store/payment_status.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="/shop.html">Shop</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'store:cart' %}">Cart</a></li>
                        <li class="breadcrumb-item"><a href="/checkout.html">Checkout</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Payment Status</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle" style="margin-bottom: 600px;">
    <div class="container">
        <div class="row justify-content-center">
            
        </div>
        <div class="row justify-content-center">
            
            <div class="col-12 col-md-10 col-lg-12 col-xl-12 text-center">
                {% if payment_status == "paid" %}
                    <!-- Icon -->
                    <div class="p-4 d-inline-flex align-items-center justify-content-center circle bg-light-primary text-success mx-auto mb-4"><i class="fas fa-heart fs-lg"></i></div>
                    <!-- Heading -->
                    <h2 class="mb-2 ft-bold">Order Completed!</h2>
                    <!-- Text -->
                    <p class="ft-regular fs-md mb-5">Your order <span class="text-body text-dark fw-bold">#{{order.order_id}}</span> has been completed. <br> we have sent the order details to your email.</p>
                    <!-- Button -->
                    <a href="{% url 'customer:order_detail' order.order_id %}" class="btn btn-sm rounded text-white bg-success">View Orders</a>
                {% endif %}
            </div>

            <div class="col-12 col-md-10 col-lg-8 col-xl-6 text-center">
                    {% if payment_status == "failed" %}
                        <!-- Icon -->
                        <div class="p-4 d-inline-flex align-items-center justify-content-center circle bg-light-danger text-danger mx-auto mb-4"><i class="fas fa-ban fs-lg"></i></div>
                        <!-- Heading -->
                        <h2 class="mb-2 ft-bold">Order Payment Failed!</h2>
                        <!-- Text -->
                        <p class="ft-regular fs-md mb-5">Your order couldn't be completed, try again later.</p>
                        <!-- Button -->
                        <a href="" class="btn btn-sm rounded text-white bg-danger">Try Again <i class="fas fa-rotate ms-2"></i></a>
                    {% endif %}
            </div>
                
        </div>
    </div>
</section>

{% endblock content %}